import {useState} from 'react';
import {lessons} from '../data/lessons';
import {useStore,update,defaultRequest} from '../store';
import {MathView} from '../components/Math';
import {Icon} from '../components/Icon';
export function Courses({id,go}:{id?:string;go:(page:string)=>void}){
 const state=useStore();const [search,setSearch]=useState('');const lesson=lessons.find(l=>l.id===id);
 if(lesson)return <article className="lesson animate-in"><button className="text-button" onClick={()=>go('cours')}><Icon name="back"/>Tous les chapitres</button><header className="page-heading"><div><p className="eyebrow">FICHE DE MÉTHODE · {lesson.minutes} MIN</p><h1>{lesson.title}</h1><p>{lesson.intro}</p></div></header>
 <div className="lesson-grid"><div>{lesson.parts.map((part,i)=><section className="lesson-part" key={i}><div className="eyebrow">PRINCIPE {i+1}</div><h2>{part.title}</h2><p>{part.text}</p><MathView tex={part.formula}/></section>)}
 <section className="worked-example"><p className="eyebrow">UN EXEMPLE POUR COMPRENDRE</p><h2>Appliquer, étape par étape</h2><ol className="steps">{lesson.worked.map((s,i)=><li key={i}><span className="step-number">{i+1}</span><div><h3>{s.title}</h3><p>{s.text}</p><MathView tex={s.formula}/></div></li>)}</ol></section></div>
 <aside className="lesson-aside"><div className="sticky-card"><Icon name="book" size={28}/><h3>Le point de vigilance</h3><p>{lesson.trap}</p><button className="button primary" onClick={()=>{update({draft:{...defaultRequest(lesson.tool),expression:lesson.example}});go('resoudre');}}>Ouvrir l’outil<Icon name="arrow"/></button><button className="button secondary" onClick={()=>go('bac/'+lesson.id)}>S’entraîner sur ce chapitre</button><button className={'text-button '+(state.read.includes(lesson.id)?'success':'')} onClick={()=>update(s=>({read:s.read.includes(lesson.id)?s.read.filter(x=>x!==lesson.id):[...s.read,lesson.id]}))}><Icon name={state.read.includes(lesson.id)?'check':'bookmark'}/>{state.read.includes(lesson.id)?'Chapitre marqué comme lu':'Marquer comme lu'}</button></div></aside></div></article>;
 const filtered=lessons.filter(l=>l.series.includes(state.series)&&(!search||(l.title+' '+l.intro).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').includes(search.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,''))));
 return <div className="animate-in"><header className="page-heading"><div><p className="eyebrow">LES MÉTHODES ESSENTIELLES</p><h1>Comprendre avant<br/>de <em>mémoriser.</em></h1></div><p>Définitions, formules, exemples corrigés et erreurs à éviter. Un parcours adapté à ta série {state.series}.</p></header><div className="catalog-heading"><span>{filtered.length} chapitres disponibles</span><label className="search"><Icon name="search"/><input aria-label="Rechercher un chapitre" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Rechercher une méthode"/></label></div><div className="course-list">{filtered.map((l,i)=><button className="course-row" key={l.id} onClick={()=>go('cours/'+l.id)}><span className="course-index">{String(i+1).padStart(2,'0')}</span><div><h2>{l.title}</h2><p>{l.intro}</p></div><span className="course-duration">{state.read.includes(l.id)?<Icon name="check"/>:<>{l.minutes} min</>}</span><Icon name="arrow"/></button>)}</div>{!filtered.length&&<p className="empty">Aucun chapitre pour cette recherche.</p>}<p className="caption">Les chapitres sont des synthèses pédagogiques originales. Les références aux programmes et aux annales sont disponibles dans l’espace Bac.</p></div>;
}
