import {useStore,update,defaultRequest} from '../store';
import {lessons} from '../data/lessons';
import {exercises} from '../data/exercises';
import {Icon} from '../components/Icon';
import {MathView} from '../components/Math';
export function Home({go}:{go:(page:string)=>void}){
 const state=useStore(),available=lessons.filter(l=>l.series.includes(state.series));
 const read=available.filter(l=>state.read.includes(l.id)).length,success=new Set(state.attempts.filter(a=>a.correct&&!a.assisted).map(a=>a.id)).size;
 const next=available.find(l=>!state.read.includes(l.id))??available[0];
 return <div className="home animate-in"><section className="hero"><div className="hero-copy"><p className="eyebrow"><span className="small-rule"/>TERMINALE · MADAGASCAR</p><h1>Un problème.<br/>Une méthode.<br/><em>Un déclic.</em></h1><p>Comprends ce qui te bloque.<br/>Avance, une étape à la fois, vers le bac.</p><button className="button primary" onClick={()=>go('resoudre')}>Résoudre un exercice<Icon name="arrow"/></button><span className="hero-footnote">Calculs, cours et entraînement disponibles hors connexion.</span></div>
 <div className="hero-figure" aria-hidden="true"><div className="figure-caption"><span>LE RAISONNEMENT PREND FORME</span><span>01 — ANALYSE</span></div><svg viewBox="0 0 480 350"><defs><pattern id="hero-grid" width="32" height="32" patternUnits="userSpaceOnUse"><path d="M32 0H0V32" fill="none" stroke="currentColor" strokeOpacity=".13"/></pattern></defs><rect x="0" y="0" width="480" height="350" fill="url(#hero-grid)"/><path d="M35 220H454 M165 25V326" stroke="currentColor" strokeOpacity=".25" strokeWidth="1"/><path className="hero-curve" d="M40 300C82 124 118 75 164 95S235 307 295 283 365 105 414 33" stroke="currentColor" strokeWidth="3" fill="none"/><path d="M165 95H318 M295 95V283" stroke="currentColor" strokeDasharray="5 6" strokeOpacity=".3"/><circle cx="165" cy="95" r="6" fill="var(--accent)" stroke="var(--paper)" strokeWidth="3"/><circle cx="295" cy="283" r="6" fill="var(--accent)" stroke="var(--paper)" strokeWidth="3"/><text x="429" y="242">x</text><text x="145" y="28">y</text><text x="180" y="82">maximum local</text></svg><div className="formula-stamp"><span>DE LA FORMULE À LA MÉTHODE</span><MathView tex="f'(x)=0"/><small>Observer. Comprendre. Démontrer.</small></div></div></section>
 <section className="home-quick"><button onClick={()=>{update({draft:{...defaultRequest('equation'),expression:'x^2-5*x+6=0'}});go('resoudre');}}><span className="quick-number">01</span><div><h3>Une équation à résoudre</h3><p>Le résultat et chaque étape.</p></div><Icon name="arrow"/></button><button onClick={()=>go('cours')}><span className="quick-number">02</span><div><h3>Une méthode à revoir</h3><p>Des explications, puis un exemple.</p></div><Icon name="arrow"/></button><button onClick={()=>go('bac')}><span className="quick-number">03</span><div><h3>Le bac en ligne de mire</h3><p>Entraînement et sujets personnels.</p></div><Icon name="arrow"/></button></section>
 <div className="home-bottom"><section><div className="section-heading"><h2>Ton prochain chapitre</h2><button className="text-button" onClick={()=>go('cours')}>Tout voir<Icon name="arrow" size={17}/></button></div><button className="next-lesson" onClick={()=>go('cours/'+next.id)}><div><p className="eyebrow">SÉRIE {state.series} · {next.minutes} MINUTES</p><h3>{next.title}</h3><p>{next.intro}</p><span className="text-link">Ouvrir la méthode<Icon name="arrow" size={18}/></span></div><span className="lesson-mark">ƒ</span></button></section><section className="progress-card"><div className="section-heading"><h2>À ton rythme</h2><Icon name="graph"/></div><div className="progress-numbers"><div><strong>{read}<small>/{available.length}</small></strong><span>chapitres lus</span></div><div><strong>{success}</strong><span>exercices réussis<br/>sans aide</span></div></div><div className="progress-track"><span style={{width:(read/available.length*100)+'%'}}/></div><p>{state.exam&&!state.exam.finished?'Une session chronométrée est en cours.':state.history.length?'Reprends un calcul enregistré dans ton carnet.':'Ton parcours commence avec le premier exercice.'}</p><button className="text-button" onClick={()=>go(state.exam&&!state.exam.finished?'bac':'carnet')}>{state.exam&&!state.exam.finished?'Reprendre la session':'Ouvrir mon carnet'}<Icon name="arrow"/></button></section></div>
 </div>;
}
