import {useRef,useState} from 'react';
import {useStore,update,restore,snapshot} from '../store';
import {saveBackup} from '../export';
import {Icon} from '../components/Icon';
export function Settings(){
 const state=useStore(),file=useRef<HTMLInputElement>(null);const [message,setMessage]=useState(''),[error,setError]=useState('');
 async function exportFile(){try{await saveBackup(JSON.stringify(snapshot(),null,2),'Maths-BAC-sauvegarde-'+new Date().toISOString().slice(0,10)+'.json');setMessage('Sauvegarde préparée. Conserve ce fichier pour restaurer ton travail.');setError('');}catch(e){setError('La sauvegarde n’a pas été exportée : '+String(e));}}
 async function importFile(f?:File){if(!f)return;try{if(f.size>3_000_000)throw new Error('Fichier trop volumineux.');const text=await f.text();if(!window.confirm('Restaurer ce fichier remplacera les données v2 de cet appareil. Continuer ?'))return;restore(text);setMessage('Sauvegarde restaurée.');setError('');}catch(e){setError(String(e).replace(/^Error: /,''));}finally{if(file.current)file.current.value='';}}
 return <div className="settings animate-in"><header className="page-heading"><div><p className="eyebrow">PRÉFÉRENCES</p><h1>Un espace<br/>à <em>ta mesure.</em></h1></div></header>
 <section className="settings-section"><h2>Confort de lecture</h2><label>Apparence<select aria-label="Apparence" value={state.theme} onChange={e=>update({theme:e.target.value as typeof state.theme})}><option value="light">Clair</option><option value="dark">Sombre</option><option value="system">Suivre l’appareil</option></select></label><label>Taille du texte <strong>{state.size} %</strong><input aria-label="Taille du texte" type="range" min="85" max="135" step="5" value={state.size} onChange={e=>update({size:Number(e.target.value)})}/></label><label className="toggle"><span><strong>Animations de transition</strong><small>Les préférences de réduction des mouvements de l’appareil sont toujours respectées.</small></span><input type="checkbox" checked={state.motion} onChange={e=>update({motion:e.target.checked})}/></label></section>
 <section className="settings-section"><h2>Sauvegarder ton travail</h2><p>Ton historique, tes favoris, tes réponses et tes notes sont stockés sur cet appareil. Exporte une sauvegarde avant de changer d’appareil ou de désinstaller l’application.</p><div className="action-row"><button className="button primary" onClick={()=>void exportFile()}><Icon name="download"/>Exporter mes données</button><button className="button secondary" onClick={()=>file.current?.click()}><Icon name="upload"/>Restaurer un fichier</button><input hidden type="file" accept=".json,application/json" ref={file} onChange={e=>void importFile(e.target.files?.[0])}/></div>{message&&<p role="status" className="notice">{message}</p>}{error&&<p className="error" role="alert">{error}</p>}</section>
 <section className="settings-section"><h2>Confidentialité</h2><div className="privacy-line"><Icon name="shield" size={30}/><p>Aucun compte, aucune publicité et aucun suivi publicitaire. Les calculs sont effectués sur ton appareil. Les liens vers les programmes et les annales ouvrent des sites externes, soumis à leurs propres règles.</p></div></section>
 <section className="settings-section about"><div><img src="./icon.svg" alt="" width="48" height="48"/><h2>Maths BAC Madagascar</h2></div><p>Version 2.2.0 · Une application indépendante pour comprendre les mathématiques et préparer le baccalauréat.</p><p className="caption">Les résultats symboliques dépendent des expressions prises en charge. Les recherches partielles sont signalées. Les graphiques et statistiques sont numériques. Cette application ne remplace ni une démonstration ni les consignes de ton professeur.</p><details><summary>Logiciels et licences</summary><p>Calcul symbolique : Nerdamer 2 (Apache-2.0). Expressions et arithmétique : math.js (Apache-2.0). Éditeur mathématique : MathLive (MIT). Formules : KaTeX (MIT). Interface : React (MIT). Application Android : Capacitor (MIT). Polices : Manrope et Newsreader (SIL Open Font License).</p></details></section>
 </div>;
}
