declare const process:{exit(code?:number):never};
import { exactLimitAtInfinity, exactElementaryBoundaryLimit } from '../src/lib/limitEngine.js';
let checks=0,failures=0;const ok=(v:boolean,l:string)=>{checks++;if(!v){failures++;console.error('FAIL',l)}};
const inf=(e:string,p:boolean,v:string)=>ok(exactLimitAtInfinity(e,p)?.value===v,`${e} ${p?'+':'-'}∞ = ${v}`);
inf('x^2',true,'+∞');inf('x^2',false,'+∞');inf('-x^3',true,'-∞');inf('-x^3',false,'+∞');
inf('1/x',true,'0');inf('(2*x^2+1)/(x^2-3)',true,'2');inf('exp(x)',true,'+∞');inf('exp(x)',false,'0');inf('exp(-x)+2',true,'2');inf('exp(-x)+2',false,'+∞');
inf('log(x)',true,'+∞');ok(exactLimitAtInfinity('log(x)',false)===null,'log x at -inf unknown/undefined');
inf('sqrt(x^2+1)',true,'+∞');inf('sqrt(x^2+1)',false,'+∞');inf('sin(1/x)',true,'0');ok(exactLimitAtInfinity('sin(x)',true)===null,'sin x no limit');ok(exactLimitAtInfinity('x*sin(x)',true)===null,'x sin x not falsely infinite');
ok(exactElementaryBoundaryLimit('log(x)',0,'right')?.value==='-∞','ln x at 0+');ok(exactElementaryBoundaryLimit('sqrt(x)',0,'right')?.value==='0','sqrt x at 0+');ok(exactElementaryBoundaryLimit('log(x)',0,'left')===null,'ln x at 0- invalid');
console.log(`Limit audit: ${checks} checks, ${failures} failure(s)`);if(failures)process.exit(1);
