import {MathView} from './Math';
import type {FunctionAnalysis as Analysis,RemarkablePoint} from '../engine/types';
const names={zero:'Zéro',minimum:'Minimum local',maximum:'Maximum local',stationary:'Point stationnaire',inflection:'Inflexion'};
function PointList({points,empty}:{points:RemarkablePoint[];empty:string}){return points.length?<div className="remarkable-list">{points.map((p,i)=><div key={i}><span>{names[p.kind]}<small>{p.exact?'Coordonnées exactes':'Coordonnées approchées'}</small></span><MathView tex={(p.exact?'':'\\approx ')+p.latex}/></div>)}</div>:<p className="analysis-empty">{empty}</p>;}
export function FunctionAnalysis({analysis:a}:{analysis:Analysis}){
 return <section className="function-analysis"><div className="section-heading"><h3>Les éléments de l’étude</h3><span>Domaine · dérivées · limites</span></div>
  <div className="analysis-formulas"><div><span className="eyebrow">DOMAINE DE DÉFINITION</span><MathView tex={a.domain}/></div><div><span className="eyebrow">DÉRIVÉE PREMIÈRE</span><MathView tex={a.derivative}/></div>{a.secondDerivative&&<div><span className="eyebrow">DÉRIVÉE SECONDE</span><MathView tex={a.secondDerivative}/></div>}</div>
  <div className="analysis-grid"><section className="analysis-tile"><div className="section-heading"><h4>Zéros de la fonction</h4><span>{a.zerosComplete?'Recherche exacte':'Fenêtre initiale'}</span></div>{a.zeroIdentity?<p>La fonction est nulle sur son domaine.</p>:<PointList points={a.zeros} empty={a.zerosComplete?'Aucun zéro réel dans le domaine.':'Aucun zéro repéré dans la fenêtre initiale. La recherche numérique peut en manquer.'}/>}</section><section className="analysis-tile"><div className="section-heading"><h4>Extrema et points stationnaires</h4><span>{a.variation==='global'?'Étude globale':'Repérage numérique'}</span></div>{a.stationaryIdentity?<p>La dérivée est nulle sur chaque intervalle du domaine : la fonction y est constante.</p>:<PointList points={a.critical} empty={a.variation==='global'?'Aucun point stationnaire dans le domaine.':'Aucun point stationnaire repéré dans la fenêtre initiale.'}/>}</section></div>
  {a.secondDerivative&&<section className="analysis-tile inflection-tile"><div className="section-heading"><h4>Points d’inflexion</h4><span>{a.curvature?.global?'Étude globale':'Fenêtre initiale'}</span></div><PointList points={a.inflections} empty={a.curvature?.global?'Aucun changement de convexité avec tangente identifié.':'Aucun point d’inflexion repéré dans la fenêtre initiale.'}/></section>}
  <section className="analysis-tile"><div className="section-heading"><h4>Asymptotes établies par les limites</h4><span>{a.asymptotes.length} droite{a.asymptotes.length>1?'s':''}</span></div>{a.asymptotes.length?<div className="asymptote-list">{a.asymptotes.map((v,i)=><div key={i}><span>{v.kind==='vertical'?'Verticale':v.kind==='horizontal'?'Horizontale':'Oblique'}<small>{v.direction}</small></span><MathView tex={v.latex}/></div>)}</div>:<p className="analysis-empty">Aucune asymptote obtenue par le calcul symbolique.</p>}</section>
  {a.limits.length>0&&<details className="analysis-limits"><summary>Voir les {a.limits.length} limites calculées</summary><div>{a.limits.map((v,i)=><div key={i}><span>{v.label}</span><MathView tex={v.latex}/></div>)}</div></details>}
 </section>;
}
